### ISSUE TITLE
add link validation to the  getInputFieldContent function

### ISSUE THREAD

**Issue by Nyior** [MLH-Fellowship/klin-url#15]
right now our input field accepts almost anything(plain text, numbers etc) as the url to be shortened.
Add some validation to verify that the content submitted is a valid url.

**Comment by gmelodie** [comment]
This should be pretty straightforward using [`urllib`](https://stackoverflow.com/a/22238205/6032037) or [`urlextract`](https://pypi.org/project/urlextract/)in python
