### ISSUE TITLE
make an API call within the shortenUrl function

### ISSUE THREAD

**Issue by Nyior** [MLH-Fellowship/klin-url#9]
In the js folder of this project you should see a shortenUrl() function.
In that function, write some code that makes an API call to an endpoint that would shorten the url and return some data.

The endpoint accepts a POST request
with a payload in the form below

```
            {
                'longUrl' : 'the url to be shortened'
            }
```

  it then returns a response in the form below:

```
        {
                'longUrl' : 'the url to be shortened',
                'klinUrl' : 'the shortened url'
            }
```
I will soon deploy our API and share the link with you. for now just make an api call to some dummy endpoint

**Comment by k07-repo** [comment]
API call itself is made in #13. Needs tuning to only be called when selected in the UI, but the call itself is there.

**Comment by k07-repo** [comment]
The API call itself is made in #13. Needs tuning to only be called when selected in the UI, but the call itself is there.
